#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <iso646.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>

/**
 * 设定插入点
 * 字符处理
 * 定义错误码
 * 浮点数处理
 * 对应各种运算符的宏
 * 定义各种数据类型最值的常量
 * 定义本地化C函数
 * 定义数学函数
 * 异常处理支持
 * 信号机制支持
 * 不定参数列表支持
 * 常用常量
 * 定义输入／输出函数
 * 定义杂项函数及内存分配函数
 * 字符串处理
 * 定义关于时间的函数
 * 宽字符处理及输入／输出
 * 宽字符分类
 */